### ISSUE TITLE
Videocontent

### ISSUE THREAD

**Issue by zettizettler** [quillie/nostr-wegweiser#3]
Nostr-Einführung mit Damus von der Blocktrainer-Community:
https://www.youtube.com/watch?v=f0nPjOqpbdE&pp=ygUFbm9zdHI%3D

Kanal der Beiträge von Nostr-Konferenzen (engl.):
https://www.youtube.com/@nostrworld

What is nostr by lnbits (engl.):
https://www.youtube.com/watch?v=5W-jtbbh3eA

How nostr works in 2 Minutes by Jack Dorsey (engl.):
https://www.youtube.com/watch?v=0YDj1QdL2Zs

How to use nostr by BTC Sessions (engl.):
https://www.youtube.com/watch?v=qn-Zp491t4Y&pp=ygUSbm9zdHIgYnRjIHNlc3Npb25z

Primal Tutorial by BTC Sessions (engl.):
https://www.youtube.com/watch?v=Qd4Po4i7wvc

Damus Tutorial by BTC Sessions (engl.):
https://www.youtube.com/watch?v=fG1IDm-lQek&pp=ygUSbm9zdHIgYnRjIHNlc3Npb25z

**Comment by quillie** [comment]
sehr wichtiger Input! thx
